### Retrieve all users

GET http://localhost:8080/users/

### Retrieve user by Id

GET http://localhost:8080/users/3

### Retrieve user by email: valid requests

GET http://localhost:8080/users/search?email=TEST@test.com

### Retrieve user by email: invalid request

GET http://localhost:8080/users/search?email=testtest.com